CREATE TABLE src(a INTEGER);
CREATE TABLE dst(a INTEGER);
CREATE PROCEDURE fill() BEGIN INSERT INTO dst SELECT a FROM src ORDER BY a; END;
.print === EXPLAIN plain INSERT..SELECT ===
EXPLAIN INSERT INTO dst SELECT a FROM src ORDER BY a;
.print === EXPLAIN CALL fill ===
EXPLAIN CALL fill();
